Repository clapsheep/walk-or-run-server, pull requests merged in 2024-11, with the labels that each got.

#10 [init] 커밋 컨벤션 및 DBConfig 경로 수정
  build.gradle
  src/main/java/com/wor/dash/WalkOrRunServerApplication.java
  src/main/java/com/wor/dash/config/DBConfig.java
  src/main/java/com/wor/dash/config/SwaggerConfig.java
Labels: ⚙️ Setting

#23 [docs] main 브랜치 수정사항 반영
  .github/workflows/deploy.yml
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#24 [deploy] CI/CD 최종 테스트
  src/main/java/com/wor/Test.java
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#25 [deploy] CI/CD 최종 테스트
  src/main/java/com/wor/Test.java
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#26 [deploy] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#27 [deploy] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#28 [docs] deploy.yml
  .github/workflows/deploy.yml
Labels: 📑 Docs

#29 [docs] deploy.yml
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#30 [docs] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#31 [docs] deploy.yml 수정
  .github/workflows/deploy.yml
Labels: ❌ Bug, 📑 Docs, 🌎 Deploy

#33 [feat] JWT 토큰, Spring Security 로직 구현
  build.gradle
  src/main/java/com/wor/Test.java
  src/main/java/com/wor/dash/WalkOrRunServerApplication.java
  src/main/java/com/wor/dash/aop/ExecutionTimeAspect.java
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/jwt/config/CustomLogoutHandler.java
  src/main/java/com/wor/dash/jwt/controller/AuthenticationController.java
  src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/wor/dash/jwt/model/Token.java
  src/main/java/com/wor/dash/jwt/model/dao/TokenMapper.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationService.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/JwtService.java
  src/main/java/com/wor/dash/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/TokenService.java
  src/main/java/com/wor/dash/jwt/model/service/TokenServiceImp.java
  src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
  src/main/java/com/wor/dash/response/ApiResponse.java
  src/main/java/com/wor/dash/response/AuthenticationResponse.java
  src/main/java/com/wor/dash/user/model/CustomUserDetails.java
  src/main/java/com/wor/dash/user/model/User.java
  src/main/java/com/wor/dash/user/model/dao/UserMapper.java
  src/main/java/com/wor/dash/user/model/service/UserService.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mapper/TokenMapper.xml
  src/main/resources/mapper/UserMapper.xml
  src/test/java/com/wor/WalkOrRunServerApplicationTests.java
Labels: 🚧 Feature

#38 [feat] Comment 기능 구현
  build.gradle
  src/main/java/com/wor/dash/comment/model/controller/CommentController.java
  src/main/java/com/wor/dash/comment/model/service/CommentServiceImpl.java
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/mapper/CommentMapper.xml
  src/test/java/com/wor/WalkOrRunServerApplicationTests.java
Labels: 🚧 Feature

#40 [refator] 복수 명사 수정 및 불필요한 secruity 해제
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/config/SwaggerConfig.java
  src/main/java/com/wor/dash/config/WebMvcConfiguration.java
  src/main/java/com/wor/dash/jwt/controller/AuthenticationController.java
  src/main/java/com/wor/dash/record/model/Calorie.java
  src/main/java/com/wor/dash/record/model/Distance.java
  src/main/java/com/wor/dash/record/model/HeartRate.java
  src/main/java/com/wor/dash/record/model/Speed.java
  src/main/java/com/wor/dash/record/model/Step.java
  src/main/java/com/wor/dash/record/model/Time.java
  src/main/java/com/wor/dash/record/model/controller/RecordController.java
  src/main/java/com/wor/dash/record/model/mapper/RecordMapper.java
  src/main/java/com/wor/dash/record/model/service/CalorieService.java
  src/main/java/com/wor/dash/record/model/service/CalorieServiceImpl.java
  src/main/java/com/wor/dash/record/model/service/DistanceService.java
  src/main/java/com/wor/dash/record/model/service/DistanceServiceImpl.java
  src/main/java/com/wor/dash/record/model/service/HeartRateService.java
  src/main/java/com/wor/dash/record/model/service/HeartRateServiceImpl.java
  src/main/java/com/wor/dash/record/model/service/SpeedService.java
  src/main/java/com/wor/dash/record/model/service/SpeedServiceImpl.java
  src/main/java/com/wor/dash/record/model/service/StepService.java
  src/main/java/com/wor/dash/record/model/service/StepServiceImpl.java
  src/main/java/com/wor/dash/record/model/service/TimeService.java
  src/main/java/com/wor/dash/record/model/service/TimeServiceImpl.java
  src/main/java/com/wor/dash/records/model/mapper/RecordsMapper.java
  src/main/java/com/wor/dash/records/model/service/CalorieService.java
  src/main/java/com/wor/dash/records/model/service/DistanceService.java
  src/main/java/com/wor/dash/records/model/service/HeartRateService.java
  src/main/java/com/wor/dash/records/model/service/SpeedService.java
  src/main/java/com/wor/dash/records/model/service/StepService.java
  src/main/java/com/wor/dash/records/model/service/TimeService.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/resources/mapper/CommentMapper.xml
Labels: 🛠️ Refactor

#39 [refactor] 컨트롤러 이름 및 위치 변경
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/jwt/model/TokenSelective.java
  src/main/java/com/wor/dash/jwt/model/mapper/TokenMapper.java
  src/main/java/com/wor/dash/jwt/model/service/TokenServiceImp.java
  src/main/java/com/wor/dash/password/model/PasswordFindQnA.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
  src/main/resources/mapper/TokenMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#43 [feat] Follow 기능 구현
  src/main/java/com/wor/dash/comment/model/controller/CommentController.java
  src/main/java/com/wor/dash/follow/model/Follow.java
  src/main/java/com/wor/dash/follow/model/controller/FollowController.java
  src/main/java/com/wor/dash/follow/model/mapper/FollowMapper.java
  src/main/java/com/wor/dash/follow/model/service/FollowService.java
  src/main/java/com/wor/dash/follow/model/service/FollowServiceImpl.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/mapper/FollowMapper.xml
Labels: 🚧 Feature

#52 [feat] 팔로우, 코멘트 기능 테스트 및 스웨거 문서작성
  src/main/java/com/wor/Test.java
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/resources/mapper/CommentMapper.xml
Labels: ❌ Bug, 🚧 Feature

#59 [feat] Comment 페이지네이션 구현
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/java/com/wor/dash/comment/model/Comment.java
  src/main/java/com/wor/dash/comment/model/mapper/CommentMapper.java
  src/main/java/com/wor/dash/comment/model/service/CommentService.java
  src/main/java/com/wor/dash/comment/model/service/CommentServiceImpl.java
  src/main/resources/mapper/CommentMapper.xml
Labels: 🚧 Feature

#60 [feat] update details of User System
  src/main/java/com/wor/dash/WalkOrRunServerApplication.java
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/MyChallenge.java
  src/main/java/com/wor/dash/user/model/User.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/java/com/wor/dash/user/model/service/UserService.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#63 [docs] Swagger API 문서 추가
  src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/follow/controller/FollowController.java
  src/main/java/com/wor/dash/password/controller/PasswordController.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
Labels: 📑 Docs

#64 [feat] userGoal 기능 구현
  src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
  src/main/java/com/wor/dash/userGoal/model/UserGoal.java
  src/main/java/com/wor/dash/userGoal/model/mapper/UserGoalMapper.java
  src/main/java/com/wor/dash/userGoal/model/service/UserGoalService.java
  src/main/java/com/wor/dash/userGoal/model/service/UserGoalServiceImpl.java
  src/main/resources/mapper/UserGoalMapper.xml
Labels: 🚧 Feature

#66 [feat] csv 날짜 파싱
  build.gradle
  src/main/java/com/wor/dash/follow/model/Follow.java
  src/main/java/com/wor/dash/record/controller/RecordController.java
  src/main/java/com/wor/dash/record/model/Calorie.java
  src/main/java/com/wor/dash/record/model/Record.java
  src/main/java/com/wor/dash/record/model/mapper/RecordMapper.java
  src/main/java/com/wor/dash/record/model/service/RecordService.java
  src/main/java/com/wor/dash/record/model/service/RecordServiceImpl.java
  src/main/resources/mapper/RecordMapper.xml
Labels: 🚧 Feature

#67 [refactor] UserGoal API 명세서 작성
  src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
  src/main/resources/mapper/UserGoalMapper.xml
Labels: 🚧 Feature

#65 [feat] challenge 스케쥴러 기능 개발
  build.gradle
  src/main/java/com/wor/dash/WalkOrRunServerApplication.java
  src/main/java/com/wor/dash/challenge/model/Challenge.java
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/java/com/wor/dash/config/SchedulerConfig.java
  src/main/java/com/wor/dash/util/DateTimeUtil.java
  src/main/resources/mapper/ChallengeMapper.xml
Labels: 🚧 Feature

#72 [refactor] Comment, UserGoal, Follow API 수정
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/java/com/wor/dash/comment/model/mapper/CommentMapper.java
  src/main/java/com/wor/dash/comment/model/service/CommentService.java
  src/main/java/com/wor/dash/comment/model/service/CommentServiceImpl.java
  src/main/java/com/wor/dash/follow/controller/FollowController.java
  src/main/java/com/wor/dash/follow/model/mapper/FollowMapper.java
  src/main/java/com/wor/dash/follow/model/service/FollowService.java
  src/main/java/com/wor/dash/follow/model/service/FollowServiceImpl.java
  src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
  src/main/java/com/wor/dash/userGoal/model/mapper/UserGoalMapper.java
  src/main/java/com/wor/dash/userGoal/model/service/UserGoalService.java
  src/main/java/com/wor/dash/userGoal/model/service/UserGoalServiceImpl.java
  src/main/resources/mapper/CommentMapper.xml
  src/main/resources/mapper/FollowMapper.xml
  src/main/resources/mapper/UserGoalMapper.xml
Labels: 🛠️ Refactor

#73 [feat] Challenge Scheduler 기능 구현
  src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
  src/main/java/com/wor/dash/challenge/model/Challenge.java
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/java/com/wor/dash/config/SchedulerConfig.java
  src/main/java/com/wor/dash/follow/controller/FollowController.java
  src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
  src/main/java/com/wor/dash/util/CronUtil.java
  src/main/resources/mapper/ChallengeMapper.xml
Labels: 🚧 Feature

#78 [feat] 유저 세부기능 수정 및 검색기능 추가
  src/main/java/com/wor/dash/config/EncoderConfig.java
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationService.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
  src/main/java/com/wor/dash/password/PasswordChangeUtil.java
  src/main/java/com/wor/dash/password/controller/PasswordController.java
  src/main/java/com/wor/dash/search/model/SearchServiceImp.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/MyChallenge.java
  src/main/java/com/wor/dash/user/model/User.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/java/com/wor/dash/user/model/service/UserService.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
  src/main/resources/mapper/PasswordMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#77 [refactor] challenge Service 메서드명 변경 (복수형 -> List) 및 사용 안하는 파일 삭제
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/java/com/wor/dash/util/CronUtil.java
  src/main/resources/mapper/ChallengeMapper.xml
Labels: 🛠️ Refactor

#81 [feat] 페이징 기능 구현
  src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/java/com/wor/dash/search/controller/SearchController.java
  src/main/java/com/wor/dash/search/model/SearchService.java
  src/main/java/com/wor/dash/search/model/SearchServiceImp.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/resources/mapper/ChallengeMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#79 [refactor] 메서드명 변경 후 에러 해결
  src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
  src/main/java/com/wor/dash/challenge/model/Challenge.java
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/resources/mapper/ChallengeMapper.xml
Labels: 🛠️ Refactor

#84 [refactor] 모든 문제 해결(아마)
  src/main/java/com/wor/dash/WalkOrRunServerApplication.java
  src/main/java/com/wor/dash/aop/ExecutionTimeAspect.java
  src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
  src/main/java/com/wor/dash/challenge/model/Challenge.java
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/java/com/wor/dash/comment/model/mapper/CommentMapper.java
  src/main/java/com/wor/dash/comment/model/service/CommentServiceImpl.java
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/config/SwaggerConfig.java
  src/main/java/com/wor/dash/follow/model/mapper/FollowMapper.java
  src/main/java/com/wor/dash/follow/model/service/FollowServiceImpl.java
  src/main/java/com/wor/dash/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/wor/dash/jwt/model/mapper/TokenMapper.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationService.java
  src/main/java/com/wor/dash/jwt/model/service/AuthenticationServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/JwtService.java
  src/main/java/com/wor/dash/jwt/model/service/JwtServiceImpl.java
  src/main/java/com/wor/dash/jwt/model/service/TokenService.java
  src/main/java/com/wor/dash/jwt/model/service/TokenServiceImp.java
  src/main/java/com/wor/dash/jwt/model/service/UserDetailServiceImpl.java
  src/main/java/com/wor/dash/password/controller/PasswordController.java
  src/main/java/com/wor/dash/password/model/mapper/PasswordMapper.java
  src/main/java/com/wor/dash/password/model/service/PasswordService.java
  src/main/java/com/wor/dash/password/model/service/PasswordServiceImpl.java
  src/main/java/com/wor/dash/record/controller/RecordController.java
  src/main/java/com/wor/dash/response/AuthenticationResponse.java
  src/main/java/com/wor/dash/search/controller/SearchController.java
  src/main/java/com/wor/dash/search/model/SearchService.java
  src/main/java/com/wor/dash/search/model/SearchServiceImp.java
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/CustomUserDetails.java
  src/main/java/com/wor/dash/user/model/User.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/java/com/wor/dash/user/model/service/UserService.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
  src/main/java/com/wor/dash/userGoal/controller/UserGoalController.java
  src/main/java/com/wor/dash/userGoal/model/service/UserGoalServiceImpl.java
  src/main/resources/mapper/ChallengeMapper.xml
  src/main/resources/mapper/PasswordMapper.xml
  src/main/resources/mapper/RecordMapper.xml
  src/main/resources/mapper/TokenMapper.xml
  src/main/resources/mapper/UserMapper.xml
Labels: 🛠️ Refactor

#85 [feat] 회원가입 시 이메일 중복확인 기능 추가
  src/main/java/com/wor/dash/user/controller/UserController.java
  src/main/java/com/wor/dash/user/model/mapper/UserMapper.java
  src/main/java/com/wor/dash/user/model/service/UserService.java
  src/main/java/com/wor/dash/user/model/service/UserServiceImpl.java
  src/main/resources/mapper/UserMapper.xml
Labels: 🚧 Feature

#88 [refactor] 프론트 개발을 위한 CORS 개방
  src/main/java/com/wor/dash/comment/controller/CommentController.java
  src/main/java/com/wor/dash/follow/controller/FollowController.java
  src/main/java/com/wor/dash/password/controller/PasswordController.java
  src/main/java/com/wor/dash/record/controller/RecordController.java
Labels: 🚧 Feature

#90 [refactor] MySQL 보안방식 설정
  src/main/resources/application.yml
Labels: 🌎 Deploy

#91 [refactor] MySQL 보안방식 설정
  src/main/resources/application.yml
Labels: 🌎 Deploy

#92 [refactor] SecurityConfig 권한 제한, 엔드포인트 및 파라미터 수정
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/password/controller/PasswordController.java
  src/main/java/com/wor/dash/user/controller/UserController.java
Labels: 🛠️ Refactor

#93 [deploy] 배포를 위한 pull request
  src/main/java/com/wor/dash/config/SecurityConfig.java
  src/main/java/com/wor/dash/password/controller/PasswordController.java
  src/main/java/com/wor/dash/user/controller/UserController.java
Labels: 🌎 Deploy

#145 [refactor] 스웨거 Cors 배포 사이트 허용
  src/main/java/com/wor/dash/config/WebMvcConfiguration.java
  src/main/resources/application.yml
Labels: 🛠️ Refactor

#146 [deploy] 스웨거 Cors 배포 사이트 허용
  src/main/java/com/wor/dash/config/WebMvcConfiguration.java
  src/main/resources/application.yml
Labels: 🌎 Deploy

#148 [refactor] 스웨거 Cors 배포 사이트 허용2
  src/main/java/com/wor/dash/config/SwaggerConfig.java
  src/main/java/com/wor/dash/config/WebMvcConfiguration.java
Labels: 🌎 Deploy

#151 [refactor] Challenge 상세조회 데이터 수정
  src/main/java/com/wor/dash/challenge/controller/ChallengeController.java
  src/main/java/com/wor/dash/challenge/model/Challenge.java
  src/main/java/com/wor/dash/challenge/model/mapper/ChallengeMapper.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeService.java
  src/main/java/com/wor/dash/challenge/model/service/ChallengeServiceImpl.java
  src/main/resources/mapper/ChallengeMapper.xml
Labels: 🛠️ Refactor
